name: Main workflow

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  workflow:
    runs-on: ubuntu-latest
    container: texlive/texlive:TL2020-historic
    steps:
    
    - name: Clone the reference repository
      uses: actions/checkout@v2

    - name: Setup pip
      run: |
        apt update
        apt install python3-pip -y

    - name: Install black
      run: |
        pip install black[jupyter]

    - name: Check code formatting of notebooks
      run: |
        black --check --verbose notebooks/book1/*.ipynb
        black --check --verbose notebooks/book2/*.ipynb
    
    - name: Install pytest and jupyter
      run: |
        pip install pytest jupyter

    - name: Check notebooks for errors
      run: |
        pytest -s --verbose tests/test_notebooks.py

    - name: Push figures to auto_generated_figures (does not run on pull requests)
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: figures/
        publish_branch: auto_generated_figures
      if: github.event_name == 'push'  # Don't run on pull requests